name: Dart CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Flutter Test
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test action
        uses: ./
        with:
          credential: "{}"
          package_directory: "./"
          skip_test: false
          dry_run: true
